Implement common ES logger
matrixbotio/go-common-lib pull request #1
Opened 2022-06-13 07:52 UTC by NikitaZhdanov

2022-06-13 07:58 UTC, KaMeHb-UA approved these changes

2022-06-13 07:58 UTC, Rhettwind approved these changes

2022-06-13 13:37 UTC, Sagleft requested changes
либу ES надо использовать версии v7.13.1
тогда не будет ошибки с "ваш софт не софт"

2022-06-14 09:05 UTC, Sagleft requested changes

2022-06-14 09:05 UTC, Sagleft commented on logger.go
> +type esLogger struct {
дублирующаяся приставка. то, что эти поля имеют отношение к ES, и так понятно. поэтому можно у полей упустить "es"

2022-06-14 11:12 UTC, NikitaZhdanov commented on logger.go
> +type esLogger struct {
fixed, thanks

2022-06-14 11:31 UTC, Sagleft approved these changes

2022-06-15 07:01 UTC, merged