Zap: change to custom logic with different logger levels
matrixbotio/go-common-lib pull request #15
Opened 2022-08-15 23:42 UTC by alex-dwt

2022-08-16 09:04 UTC, NikitaZhdanov requested changes

2022-08-16 09:04 UTC, NikitaZhdanov commented on cmd/zes/main.go
> +	debugLgr := logger.New(zap.DebugLevel)
Все-таки подход "я даже не буду разбираться в том что вы понаписали" даёт о себе знать.

У нас реализовано по-другому: https://github.com/matrixbotio/go-common-lib/blob/master/logger/helpers.go#L108 - тут считываются все env vars LOG_LEVEL_*

А тут проверяется уровень логирования с учётом этих настроек: https://github.com/matrixbotio/go-common-lib/blob/master/logger/logger.go#L50

И не нужно в коде приложения прописывать каждый раз новый логгер, в случае если необходимо поменять уровень для конкретного пакета или метода

2022-08-16 18:01 UTC, alex-dwt commented on cmd/zes/main.go
> +	debugLgr := logger.New(zap.DebugLevel)
**И не нужно в коде приложения прописывать каждый раз новый логгер, в случае если необходимо поменять уровень для конкретного пакета или метода**

похорошему   - юзается   DI
он создает все зависимости и логгеры и все все
вот в логику где зависимости создаются - туда и нужно IFs  запихать   что бы   они создали нужный (основываясь на чем хотите)
для меня - это самый очевидный вариант...

2022-08-18 04:58 UTC, NikitaZhdanov approved these changes

2022-08-18 11:00 UTC, Sagleft approved these changes

2022-08-18 11:00 UTC, merged