add review and test github actions
matrixbotio/go-common-lib pull request #3
Opened 2022-06-13 09:57 UTC by NikitaZhdanov

2022-06-13 13:42 UTC, Sagleft commented on .github/workflows/test.yml
> +          go-version: '1.16'
лучше поставить 1.17 заранее
например, если понадобится работать с unix timestamp ms, то в 1.16 нет метода UnixMilli

2022-06-13 13:43 UTC, Sagleft requested changes
go version

2022-06-14 09:02 UTC, Sagleft approved these changes

2022-06-20 06:57 UTC, KaMeHb-UA requested changes
https://matrixbotio.slack.com/archives/C03JDNADAH2/p1655707581065439?thread_ts=1655114223.541679&cid=C03JDNADAH2

2022-06-21 15:49 UTC, merged